- README.md
This adds a brief instruction on how to build with the released 5.6 toolchains.
> Add instructions for building with swift 5.6 toolchains

- Sources/AsyncAlgorithms/AsyncBufferSequence.swift
- Sources/AsyncAlgorithms/AsyncChain2Sequence.swift
- Sources/AsyncAlgorithms/AsyncChain3Sequence.swift
- Sources/AsyncAlgorithms/AsyncDebounceSequence.swift
- Sources/AsyncAlgorithms/AsyncLazySequence.swift
- Sources/AsyncAlgorithms/AsyncMerge2Sequence.swift
- Sources/AsyncAlgorithms/AsyncMerge3Sequence.swift
- Sources/AsyncAlgorithms/Rethrow.swift
- Sources/AsyncSequenceValidation/WorkQueue.swift
This PR fixes a few typos across various comments in the code.
> Fixing a few typos

- Tests/AsyncAlgorithmsTests/Performance/TestThroughput.swift
- Tests/AsyncAlgorithmsTests/Performance/ThroughputMeasurement.swift
This PR extends `measureSequenceThroughput` to take two outputs so functions like merge/ zip etc can be tested by both sides.
> #45 - Two sided performance test for merge

- README.md
This PR fixes the link in the `README.md` file to point to the right page in the Swift Forums.
> Fix the link to the project in the Swift Forums

- Tests/AsyncAlgorithmsTests/Performance/ThroughputMeasurement.swift
`duration` and `start` property in `measureSequenceThroughput` is [vestigial from early development](https://github.com/apple/swift-async-algorithms/pull/114#discussion_r836947233). This PR cleans that up.
> Remove obsolete property from measureSequenceThroughput

- Guides/AdjacentPairs.md
- Guides/Effects.md
- README.md
- Sources/AsyncAlgorithms/AdjacentPairsSequence.swift
- Tests/AsyncAlgorithmsTests/TestAdjacentPairs.swift
Similarly to swift-algorithms package [introduced](https://github.com/apple/swift-algorithms/pull/119) `adjacentPairs()`, it's equally relevant in the async/await world. 
I took inspiration from their implementation and updated the relevant documentation.
> Adjacent Pairs

- Guides/Collections.md
- Tests/AsyncAlgorithmsTests/TestRangeReplaceableCollection.swift
Renames `TestRangeReplacableCollection.swift` to `TestRangeReplaceableCollection.swift`.
> Fix `TestRangeReplaceableCollection.swift` file name

- Guides/Throttle.md
- Sources/AsyncAlgorithms/AsyncThrottleSequence.swift
- Sources/AsyncSequenceValidation/Expectation.swift
- Tests/AsyncAlgorithmsTests/TestThrottle.swift
This resolves #113 by defining the first element as not exceeding the reduction of the duration. 
Fixing that caused a related issue with the validation reconstruction to show a mis-alignment of the events.
> #113 Define the first element of throttled sequences by not exceeding  the rate (and fix a expectation misalignment of events)

- Guides/Merge.md
I found a Swift syntax error in the guide and fixed it.
> Fix merge example

- Sources/AsyncAlgorithms/AsyncBufferedByteIterator.swift
This resolves issue #120 by ensuring the shared buffers are reloaded independently. This does not promise any data consistency across tasks, but does ensure that the iteration can be sent as a move from one task to another.
> #120 Ensure concurrent access to `AsyncBufferedByteIterator` does not crash from dangling pointers

- Sources/AsyncAlgorithms/AsyncChannel.swift
- Sources/AsyncAlgorithms/AsyncThrowingChannel.swift
- Tests/AsyncAlgorithmsTests/TestChannel.swift
This makes AsyncChannel and AsyncThrowing channel no longer cause tasks to hang when they are cancelled.
> #131 Cancel sends as if they were terminal events on task cancellation

- Sources/AsyncAlgorithms/AsyncAlgorithms.docc/Guides/Chain.md
To fix some typos in the `Chain.md` file:
- Syntax errors in the example code
- Grammatical phrase
> Fix some typos in Chain.md

- README.md
To fix the broken links to the guides in README.md (their location changed to support the DocC changes).
> Fix broken links to guides in README.md

- Sources/AsyncAlgorithms/AsyncChannel.swift
This PR fixes potential crashes where the state is "awaiting" while there are no more awaiting clients.
The state is now set to .idle to reflect the reality.
This PR is linked to the issue #142.
The fix prevents the `removeFirst()` to be executed by preemptively setting the state to a correct value. It think the `removeFirst()` statements should be used in a more secure fashion though. It could be the subject of another PR.
It is hard to produce unit tests that ensure the crashes are fixed since we must set the AsyncChannel in an awaiting state. Ideas are welcome  !
> `AsyncChannel` fixes potential crashes when no more awaiting

- Sources/AsyncAlgorithms/AsyncThrowingChannel.swift
This PR is the sister from this one https://github.com/apple/swift-async-algorithms/pull/143 but for `AsyncThrowingChannel` that suffers from the very same issue.
The issue is described here: https://github.com/apple/swift-async-algorithms/issues/142
Before this PR, an `AsyncThrowingChannel` could crash in the following context:
- start an iteration in a Task
- cancel the task while the `AsyncThrowingChannel` is being awaited
- send a value in the channel
An issue has already been created to track the implementation of unit tests to ensure non regression: https://github.com/apple/swift-async-algorithms/issues/148
> asyncThrowingChannel: fixes potential crashes when no more awaiting

- Tests/AsyncAlgorithmsTests/TestZip.swift
Hi,
This PR is a try to clarify/harmonize the unit tests for the `zip` functions.
the convention for test names is: `func test_systemUnderTest_expectedResult_when_conditionsOfTest() {}`
The pattern : `expected` / `actual/collected` has been extended to all tests.
If this initiative is successful then we could apply the same convention to other tests.
> zip: improve unit tests readability

- Sources/AsyncAlgorithms/AsyncChannel.swift
- Sources/AsyncAlgorithms/AsyncChunkedByGroupSequence.swift
Fixed a few grammatical/spacing typos and one missing line of sample code.
> Minor documentation improvements

- Sources/AsyncAlgorithms/AsyncAlgorithms.docc/Guides/Channel.md
- Sources/AsyncAlgorithms/AsyncChannel.swift
- Sources/AsyncAlgorithms/AsyncThrowingChannel.swift
- Tests/AsyncAlgorithmsTests/TestChannel.swift
This PR aims to fix/improve the "finish" strategy for `AsyncChannel`/`AsyncThrowingChannel`.
From my understanding there are two possible scenarios when sending a finish:
**- 1:** There are no awaiting clients. There are potential pending "send" operations. We send finish 1 or several times.
**- 2:** There are no pending operations. There are several awaiting clients. We send finish 1 or several times.
The current behaviour is:
**- 1:** The state is set to `terminal`. Finish is added as a pending operation (other future finishes or values will be discarded). The future clients will consume the pending operations until they reach the finish operation. Once a client has consumed this finish operation, the next potential awaiting clients will be suspended for ever.
**- 2:** The state is set …
> Fix async channel finishes all

- Tests/AsyncAlgorithmsTests/TestCompacted.swift
This PR intends to improve the unit tests naming, just as we did for the zip, merge operator.
> [Compacted] rename unit tests

- Sources/AsyncAlgorithms/AsyncAlgorithms.docc/Guides/Channel.md
- Sources/AsyncAlgorithms/AsyncChannel.swift
- Sources/AsyncAlgorithms/AsyncThrowingChannel.swift
- Tests/AsyncAlgorithmsTests/TestChannel.swift
This PR is the sister of https://github.com/apple/swift-async-algorithms/pull/152 and is linked to that issue https://github.com/apple/swift-async-algorithms/issues/155.
Long story short: terminal events (finish/fail) should not imply a back pressure management since no further elements can be sent.
When fail is called:
- all pending and awaiting operations should be immediately resumed (in order to avoid potential infinite suspensions)
- further calls to `next()` will throw the error
- further calls to `send(_:)` will immediately resume
> [AsyncThrowingChannel] make the `fail` terminal event non async

- Sources/AsyncSequenceValidation/AsyncSequenceValidation.docc/Validation.md
I think we need to add escaping characters before ` |`.
> Fix typo in Validation.md

- Evolution/0004-joined.md
- Evolution/NNNN-joined.md
This adds a proposal for the `joined` and `joined(separator:)` algorithms
@phausler Could you check if there is anything missing. Also is it fine to have you as the author of the proposal since you implemented the algo?
Read the full proposal [here](https://github.com/apple/swift-async-algorithms/blob/ebfd880ca524ef09f4bc924464adcf593a8a05e4/Evolution/NNNN-joined.md)
> Proposal for `joined` and `joined(separator:)`

- Evolution/0006-combineLatest.md
- Evolution/NNNN-combineLatest.md
Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/pr/combine_latest_proposal/Evolution/NNNN-combineLatest.md).
> Add an introduction and formatting for the `combineLatest` algorithm into a proposal.

- Tests/AsyncAlgorithmsTests/TestLazy.swift
This PR updates the unit tests to match the nomenclature of the previously merged PRs.
> AsyncLazySequence: harmonize unit tests nomenclature

- Tests/AsyncAlgorithmsTests/TestChain.swift
This PR updates the unit tests to match the nomenclature of the previously merged PRs.
> AsyncChainSequence: harmonize unit tests nomenclature

- Sources/AsyncAlgorithms/AsyncChunkedByGroupSequence.swift
- Sources/AsyncAlgorithms/AsyncChunkedOnProjectionSequence.swift
- Sources/AsyncAlgorithms/AsyncChunksOfCountSequence.swift
- Sources/AsyncAlgorithms/AsyncInterspersedSequence.swift
- Sources/AsyncAlgorithms/AsyncJoinedBySeparatorSequence.swift
- Sources/AsyncAlgorithms/AsyncJoinedSequence.swift
- Sources/AsyncAlgorithms/AsyncRemoveDuplicatesSequence.swift
Fixes #204 
To test, run 
```
xcodebuild archive -scheme AsyncAlgorithms -destination "generic/platform=iOS" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```
on this branch vs `main`. I'll note I'm building the archive with Xcode 14.0.1.
> Make initializers '@usableFromInline' instead of '@inlinable' to support building for library evolution

- Sources/AsyncAlgorithms/Zip/Zip2Runtime.swift
- Sources/AsyncAlgorithms/Zip/Zip3Runtime.swift
`withTaskCancellationHandler<T>(_:, operation:)` -> `withTaskCancellationHandler<T>(operation:onCancel:)`
One more time for the merges
> Deprecation Housekeeping (#206)

- Sources/AsyncAlgorithms/AsyncJoinedBySeparatorSequence.swift
The requirement was overly strict for AsyncJoinedBySeparatorSequence and can be safely relaxed.
> Relax Sendable conditional conformance for AsyncJoinedBySeparatorSequence

- Sources/AsyncAlgorithms/AsyncAdjacentPairsSequence.swift
We want to remove any `Sendable` constraints on iterators since they ought to not be passed between `Task`s.
Explicitly mark the `AsyncAdjacentPairsSequence` to be not `Sendable`.
Nobody can make this `Sendable`.
> Remove `Sendable` constraint for `AsyncAdjacentPairsSequence`

- Sources/AsyncAlgorithms/AsyncChain2Sequence.swift
We want to remove any `Sendable` constraints on iterators since they ought to not be passed between `Task`s.
Explicitly mark the `AsyncChain2Sequence` to be not `Sendable`.
Nobody can make this `Sendable`.
> Remove `Sendable` constraint for `AsyncChain2Sequence`

- Evolution/NNNN-bytes.md
This proposal introduces the `AsyncBufferedByteIterator` type; usable for making highly performant byte wise iteration.
Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/pr/bytes_proposal/Evolution/NNNN-bytes.md).
> Convert the bytes iterator guide to a proposal

- Sources/AsyncAlgorithms/AsyncBufferedByteIterator.swift
I raise on the pitch of `AsyncBufferedByteIterator` on the forums that I think the iterator must not be `Sendable`. The reasoning for this is twofold. First, an iterator is the connection of a consumer to the `AsyncSequence`; therefore, iterators should not be shared since it breaks that assumption. Secondly, the implementation of the `AsyncBufferedByteIterator` can be more straight forward since we don't have to check for unique ownership of the storage.
Remove the `Sendable` conformances from  `AsyncBufferedByteIterator`.
> Remove Sendable from `AsyncBufferedByteIterator`

- Tests/AsyncAlgorithmsTests/Performance/TestThroughput.swift
This PR applies the same `available` condition on TestThroughput/test_debounce() than the one on the `debounce` operator.
My environment is the following:
- macOS Monterey 12.6
- simulator iPhone 14 Pro iOS 16
The test target won't compile with the iOS simulator because of the current `available` statement.
Remark: the project does not compile since we removed the `Task.select` function (used by `combineLatest()`). I guess it is temporary waiting for the new implementation of `AsyncCombineLatestSequence`.
> [UnitTests] fix to harmonize debounce availability

- Sources/AsyncAlgorithms/AsyncChannel.swift
- Sources/AsyncAlgorithms/AsyncThrowingChannel.swift
- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStateMachine.swift
- Sources/AsyncAlgorithms/Merge/AsyncMerge2Sequence.swift
- Sources/AsyncAlgorithms/Merge/AsyncMerge3Sequence.swift
- Sources/AsyncAlgorithms/Merge/MergeStateMachine.swift
This set of changes makes sure the imports for swift-collections are an implementation detail and don't leak out to exported scopes.
> Ensure all imports of other modules are implementation only

- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStateMachine.swift
- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStorage.swift
These calls to `print` caused unexpected output to appear in apps using Async Algorithms.
> Remove `print` from implementation of `combineLatest`

- Evolution/NNNN-rate-limits.md
This proposal formalizes rate limiting algorithms for debouncing and throttling.
Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/1b7c4e9e63daa27aa7566c61980723d5b279031b/Evolution/NNNN-rate-limits.md)
> Convert the guides for debounce and throttle into a proposal

- Evolution/NNNN-chunk.md
This proposal formalizes the family of AsyncChunk* and AsyncTimer types.
Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/pr/chunk_proposal/Evolution/NNNN-chunk.md).
> Transform the chunk and timer guides into a proposal

- Evolution/NNNN-reductions.md
This proposal formalizes the family of Async*Reductions types and optimized derivatives.
Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/pr/reductions_proposal/Evolution/NNNN-reductions.md).
> Transform the reductions and remove duplicates guides into a proposal

- Evolution/NNNN-lazy.md
This proposal introduces the lazy accessors of `.async` to convert existing `Sequence` types to `AsyncSequence` types.
Read the full proposal [here](https://raw.githubusercontent.com/phausler/swift-async-algorithms/pr/lazy_proposal/Evolution/NNNN-lazy.md)
> AsyncLazySequence proposal

- Sources/AsyncAlgorithms/Locking.swift
While in the current configuration lock/unlock shouldn't ever fail, it seems polite to guard against basic misuse in debug builds.
> Add precondition guards to pthread_mutex calls

- Sources/AsyncAlgorithms/Locking.swift
This prevents the optimized versions from eliding the actual locking work from the auto closure of the precondition.
> Extract the result to test the preconditions separate from the function calls for locking

- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStateMachine.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStateMachine.swift
- Sources/AsyncAlgorithms/Merge/MergeStateMachine.swift
- Sources/AsyncAlgorithms/Zip/ZipStateMachine.swift
- Tests/AsyncAlgorithmsTests/TestCombineLatest.swift
- Tests/AsyncAlgorithmsTests/TestDebounce.swift
- Tests/AsyncAlgorithmsTests/TestMerge.swift
- Tests/AsyncAlgorithmsTests/TestZip.swift
We switched the point in time when we create tasks to the first call to `next()`. This had the side effect that we can now be cancelled before we even created our task. Which by itself is fine but we didn't handle it in the state machines.
Adapt the state machines of `debounce`, `zip`, `merge` and `combineLatest` to handle cancellation before `next()`.
We shouldn't run into these preconditions anymore.
> Tolerate cancelling before we create our task

- Evolution/0009-buffer.md
This outlines a proposal for the `AsyncBufferSequence` type used for buffering elements produced by an `AsyncSequence`.
@phausler I took the liberty of having me as an author but you should feel free to ask me to put you back as the author or co-author since you were the original one.
> Add a "new" proposal for AsyncBufferSequence

- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStateMachine.swift
- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStorage.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStateMachine.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStorage.swift
- Sources/AsyncAlgorithms/Merge/MergeStorage.swift
- Sources/AsyncAlgorithms/Zip/ZipStorage.swift
Swift 5.8 is including a change to how `group.waitForAll()` is working. It now properly waits for all tasks to finish even if one of the tasks throws. We have used `group.waitForAll()` in multiple places and need to change this code accordingly.
Switch code from `group.waitForAll()` to `group.next()`.
This fixes a few stuck tests that we have seen when running against development snapshots.
> Switch from `group.waitForAll()` to `group.next()`

- Package.swift
Rest of SwiftPM packages provided by Apple follow a dash-case naming scheme consistent with repository name, usually 
with `swift-` prefix. See attached screenshot:
> Package.swift: make package name consistent with repo name

- Evolution/0001-zip.md
- Evolution/0002-merge.md
- Evolution/0003-compacted.md
- Evolution/0004-joined.md
- Evolution/0005-adjacent-pairs.md
- Evolution/0006-combineLatest.md
- Evolution/0007-chain.md
- Evolution/0008-bytes.md
- Evolution/0009-async.md
- Evolution/0010-buffer.md
Our old proposals had a couple of stale links and were not all aligned. This cleans them up.
> Clean up old evolution proposals

- Evolution/0001-zip.md
- Evolution/0002-merge.md
- Evolution/0003-compacted.md
- Evolution/0004-joined.md
- Evolution/0005-adjacent-pairs.md
- Evolution/0006-combineLatest.md
- Evolution/0007-chain.md
- Evolution/0008-bytes.md
- Evolution/0009-async.md
- Evolution/0010-buffer.md
- Evolution/0011-interspersed.md
- Sources/AsyncAlgorithms/Interspersed/AsyncInterspersedSequence.swift
- Tests/AsyncAlgorithmsTests/Interspersed/TestInterspersed.swift
Add a new evolution proposal for the interspersed algorithm.
> Add Interspersed proposal

- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStorage.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStateMachine.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStorage.swift
- Sources/AsyncAlgorithms/Zip/ZipStorage.swift
Sorry for the minor point.
I am curious and will submit a PR.
> Rename `downStream` to `downstream`

- Sources/AsyncAlgorithms/AsyncInclusiveReductionsSequence.swift
- Sources/AsyncAlgorithms/AsyncThrowingInclusiveReductionsSequence.swift
- Sources/AsyncAlgorithms/Buffer/AsyncBufferSequence.swift
- Sources/AsyncAlgorithms/CombineLatest/AsyncCombineLatest2Sequence.swift
- Sources/AsyncAlgorithms/Debounce/AsyncDebounceSequence.swift
- Sources/AsyncAlgorithms/Interspersed/AsyncInterspersedSequence.swift
- Sources/AsyncAlgorithms/Merge/AsyncMerge2Sequence.swift
- Sources/AsyncAlgorithms/Merge/AsyncMerge3Sequence.swift
This is a comprehensive audit of the initializers and inline ABI boundaries of all API types. 
The primary entry point for all transformations is the extension to AsyncSequence unless the type is a public interface as an AsyncIteratorProtocol.
> Audit pass on inline and initialization

- Evolution/0011-interspersed.md
- Sources/AsyncAlgorithms/Interspersed/AsyncInterspersedSequence.swift
- Tests/AsyncAlgorithmsTests/Interspersed/TestInterspersed.swift
This integrates all of the feedback from the review thread. Here is a quick summary:
- Change the trailing separator behaviour. We are no longer returning a separator before we are forwarding the error
- Add a synchronous and asynchronous closure based `interspersed` method.
- Support interspersing every n elements
> [AsyncInterspersedSequence] Integrate review feedback

- Sources/AsyncSequenceValidation/Clock.swift
- Sources/AsyncSequenceValidation/Test.swift
- Tests/AsyncAlgorithmsTests/TestAdjacentPairs.swift
- Tests/AsyncAlgorithmsTests/TestBuffer.swift
- Tests/AsyncAlgorithmsTests/TestBufferedByteIterator.swift
- Tests/AsyncAlgorithmsTests/TestChain.swift
- Tests/AsyncAlgorithmsTests/TestChannel.swift
- Tests/AsyncAlgorithmsTests/TestCombineLatest.swift
- Tests/AsyncAlgorithmsTests/TestCompacted.swift
- Tests/AsyncAlgorithmsTests/TestJoin.swift
- Tests/AsyncAlgorithmsTests/TestLazy.swift
- Tests/AsyncAlgorithmsTests/TestManualClock.swift
- Tests/AsyncAlgorithmsTests/TestMerge.swift
- Tests/AsyncAlgorithmsTests/TestReductions.swift
- Tests/AsyncAlgorithmsTests/TestRemoveDuplicates.swift
- Tests/AsyncAlgorithmsTests/TestThrowingChannel.swift
- Tests/AsyncAlgorithmsTests/TestValidator.swift
- Tests/AsyncAlgorithmsTests/TestZip.swift
This resolves almost all of the warnings in the tests (except one).
> Reduce the overall warnings from tests

- Package.swift
- Sources/AsyncAlgorithms/Buffer/BoundedBufferStateMachine.swift
- Sources/AsyncAlgorithms/Buffer/UnboundedBufferStateMachine.swift
- Sources/AsyncAlgorithms/Channels/AsyncChannel.swift
- Sources/AsyncAlgorithms/Channels/AsyncThrowingChannel.swift
- Sources/AsyncAlgorithms/Channels/ChannelStateMachine.swift
- Sources/AsyncAlgorithms/Channels/ChannelStorage.swift
This brings the main API surface up to Sendable clean in complete mode. 
The primary point of change is Async(Throwing)Channel. Which previously permitted a potential Sendability soundness hole. It now requires that AsyncChannel's Element type MUST be Sendable. The reasoning is that this type's primary use case is to send elements from one isolation to another. This means that the element must be Sendable to achieve this.
> Audit pass on Sendable conformances and requirements

- Sources/AsyncAlgorithms/Locking.swift
- Sources/AsyncSequenceValidation/TaskDriver.swift
Hi everyone,
This PR adds support for WebAssembly (and possibly other single threaded environments).
I made the primitive an Int instead of a Void to avoid the `UnsafeMutablePointer<Void> has been replaced by UnsafeMutableRawPointer` warning.
<details>
<summary>Build and tests running on SwiftWasm on Linux</summary>
```
root@684f97f7b63f:/# swift --version
SwiftWasm Swift version 5.8 (swiftlang-5.8.0)
Target: x86_64-unknown-linux-gnu
root@684f97f7b63f:/# cd saa/
root@684f97f7b63f:/saa# swift build
Building for debugging...
[145/145] Merging module AsyncAlgorithms_XCTest
Build complete! (58.26s)
root@684f97f7b63f:/saa# swift test 
Building for debugging...
[50/50] Linking swift-async-algorithmsPackageTests.xctest
Build complete! (32.33s)
Test Suite 'All tests' started at 2023-06-23 …
```
> Add WebAssembly support

- Sources/AsyncAlgorithms/Merge/MergeStorage.swift
In `MergeStorage` we have the same code three times. Let's refactor it to only keep one copy of it.
> Reduce copy and paste within MergeStorage

- Sources/AsyncAlgorithms/AsyncAlgorithms.docc/Guides/Chunked.md
A comma was missing before `or:` in 
```swift
bytes.chunks(ofCount: 1024, or: .repeating(every: .seconds(1)), into: Data.self)
```
> Fix typo in Guides/Chunked.md

- Package@swift-5.7.swift
- Sources/AsyncAlgorithms/Merge/MergeStorage.swift
- Tests/AsyncAlgorithmsTests/Interspersed/TestInterspersed.swift
- Tests/AsyncAlgorithmsTests/Performance/ThroughputMeasurement.swift
- Tests/AsyncAlgorithmsTests/TestChunk.swift
We still had some `Sendable` warnings left under strict Concurrency checking.
This PR fixes a bunch of `Sendable` warnings but we still have some left in the validation tests. Additionally, I fixed a flaky test.
> Fix more `Sendable` warnings and flaky test

- Tests/AsyncAlgorithmsTests/Performance/TestThroughput.swift
- Tests/AsyncAlgorithmsTests/Support/Asserts.swift
Validating swift 5.7 build environments revealed a few minor issues with new testing adoption - this adds in an async shim for waiting for expectations and corrects a mistyped availability in the tests.
> Ensure tests work in deployments that host as swift 5.7

- Package.swift
The current validation testing library has a bunch of warnings and we haven't put it through a proper API review yet. Since we are preparing for a 1.0.0, I think it is best if we remove the products for the validation targets for now and take some time to make sure the interfaces are taken through an API review.
Remove products for the validation targets.
> Remove the validation packages from public products

- Sources/AsyncSequenceValidation/Job.swift
- Sources/AsyncSequenceValidation/Test.swift
This works-around the warnings for availability for the ExecutorJob while retaining the existing behaviors.
> Rework availability for executor to avoid warnings

- Sources/AsyncAlgorithms/AsyncChunksOfCountSequence.swift
- Tests/AsyncAlgorithmsTests/TestChunk.swift
We were failing to properly chunk a sequence if the count was `1` since we only checked for count equality on the second element but never the first one.
> Fix `chunks(countOf: 1)`

- Sources/AsyncAlgorithms/AsyncTimerSequence.swift
Currently, the `AsyncTimerSequence` is trying to correct for when an application becomes suspended and the timer might fire multiple times once the application gets foregrounded again.
However, this is already handled by the `Clock` types themselves. The `SuspendingClock` is correcting for suspension of the app whereas the `ContinuousClock` is not.
Additionally, this was not only hit by background an application but by just calling `Task.sleep` in the for-await loop that is consuming the sequence.
This removes the part of the code in `AsyncTimerSequence` which corrected for suspension of the application.
> Remove background correction in `AsyncTimerSequence`

- Evolution/NNNN-channel.md
This proposal formalizes the AsyncChannel and AsyncThrowingChannel types.
Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/pr/channel_proposal/Evolution/NNNN-channel.md).
> Add a proposal for AsyncChannel

- Sources/AsyncAlgorithms/AsyncThrottleSequence.swift
- Tests/AsyncAlgorithmsTests/TestThrottle.swift
This corrects and validates the case where the last element of a throttle is within the period of the throttle interval but no subsequent elements are produced after that terminal event.
> Ensure the last element of reduction in the throttle is emitted and use appropriate delay

- Sources/AsyncAlgorithms/Channels/AsyncChannel.swift
- Sources/AsyncAlgorithms/Channels/AsyncThrowingChannel.swift
- Sources/AsyncAlgorithms/Debounce/AsyncDebounceSequence.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStateMachine.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStorage.swift
`@unchecked Sendable` is a great way to make a type `Sendable` while it is not really `Sendable` this is rarely useful and we should rather use conditional `@unchecked Sendable` annotations such as the one on `ManagedCriticalState`
This PR removes all `@unchecked Sendable` in the main algorithm target except the one on `Merge` since we are doing manual locking there.
No more `@unchecked Sendable` usage.
> Remove majority of `@unchecked Sendable` usages

- Sources/AsyncAlgorithms/Buffer/BoundedBufferStateMachine.swift
- Sources/AsyncAlgorithms/Buffer/UnboundedBufferStateMachine.swift
- Sources/AsyncAlgorithms/Channels/ChannelStateMachine.swift
- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStateMachine.swift
- Sources/AsyncAlgorithms/Locking.swift
- Sources/AsyncAlgorithms/Merge/AsyncMerge2Sequence.swift
- Sources/AsyncAlgorithms/Merge/AsyncMerge3Sequence.swift
- Sources/AsyncAlgorithms/Merge/MergeStateMachine.swift
- Sources/AsyncSequenceValidation/TaskDriver.swift
We added `@_implementationOnly` a little while ago to hide the dependency on the `DequeModule`. However, with recent compilers this produces a warning since `@_implementationOnly` is only intended to be used in resilient libraries.
This PR removes the usage of `@_implementationOnly`
> Remove `@_implementationOnly` usage

- Sources/AsyncAlgorithms/Buffer/BoundedBufferStateMachine.swift
There was a small grammatical error which made `preconditionFailure` message a bit more misleading.
```swift
preconditionFailure("Invalid state. The task should already be started.")
```
> Fix typo in `BoundedBufferStateMachine.swift`

- Sources/AsyncAlgorithms/Buffer/BoundedBufferStorage.swift
- Sources/AsyncAlgorithms/Buffer/UnboundedBufferStorage.swift
- Sources/AsyncAlgorithms/Channels/ChannelStorage.swift
- Sources/AsyncAlgorithms/CombineLatest/CombineLatestStorage.swift
- Sources/AsyncAlgorithms/Debounce/DebounceStorage.swift
- Sources/AsyncAlgorithms/Zip/ZipStorage.swift
We wrongly assumed that it is safe to resume continuations while holding our state machine lock. There is a potential for a deadlock in rare circumstances. The problem is that the runtime holds a task specific lock. This lock is both acquired by task cancellation and continuation resumption. This can lead to scenarios where we are resuming the task's continuation while holding the state machine lock and a different thread cancelling the task and holding the runtime lock. Now both locks are held by different threads and they are waiting to acquire the opposite lock; hence, deadlocking the process.
In this PR, I went through all of our state machine based implementations and made sure that we are only acquiring the lock for as little as possible and handle all of the actions outside of the …
> Fix potential deadlocks when resuming a continuation while holding a lock

- Package.swift
Before this change, once consumers update to SwiftCollections 1.1.0 they'll pull in all of the new collection dependencies (HashTree, BitCollections, etc.). In our case, this increased our binary size by ~1MB. To fix this, we switch to only depending on what we need.
> Depend on specific products from swift-collections

- Package.swift
- Sources/AsyncAlgorithms/Buffer/BoundedBufferStateMachine.swift
- Sources/AsyncAlgorithms/Buffer/UnboundedBufferStateMachine.swift
- Sources/AsyncAlgorithms/Channels/ChannelStateMachine.swift
- Sources/AsyncAlgorithms/UnsafeTransfer.swift
There were a few new strict concurrency warnings that this PR fixes.
> Fix some strict concurrency warnings

- Sources/AsyncAlgorithms/Locking.swift
- Sources/AsyncSequenceValidation/TaskDriver.swift
Add support for Musl
Also error if platform is not recognised.
> Add Musl import, error if unrecognised platform

- Sources/AsyncAlgorithms/Locking.swift
- Sources/AsyncSequenceValidation/TaskDriver.swift
The new module and overlay were merged into Swift 6 in swiftlang/swift#74758.
I've been building and testing this package natively on Android for some time, but the addition of nullability annotations to Bionic with NDK 26 last year and the new Android overlay in the Swift compiler this summer required these changes.
> Use Bionic module from new Android overlay in Swift 6 instead

- Evolution/0006-combineLatest.md
- Evolution/0010-buffer.md
- Evolution/0011-interspersed.md
- Evolution/NNNN-rate-limits.md
- Sources/AsyncAlgorithms/Interspersed/AsyncInterspersedSequence.swift
Fixed a few typos across the documentation.
> Fix a few typos

- Sources/AsyncAlgorithms/Locking.swift
The platform lock is never deallocated, which results in a leak. Since the platform lock is owned by Lock, I thought it would be fine to make deallocation part of `deinitialize()` and not have a separate `deallocate()` function. Especially since initialization of the lock is also mixed into `allocate()` already.
> Fix memory leak in Lock

- Package.swift
The existing definitions for the versions was lifted directly from Swift-Foundation and was overly complex for AsyncAlgorithms. This simplifies it and introduces a new version id of 1.1 defined as macOS 15.0, iOS 18.0, tvOS 18.0, watchOS 11.0, visionOS 2.0 *.
> Simplify the version definitions and add a new definition for 1.1
